name: Build Minilogue XD Oscillator

on:
  push:
    branches: [master, main]
    tags: ['v*']
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Logue SDK tools
        run: |
          chmod +x ./logue-sdk/tools/gcc/get_gcc_linux.sh
          chmod +x ./logue-sdk/tools/logue-cli/get_logue_cli_linux.sh
          ./logue-sdk/tools/gcc/get_gcc_linux.sh
          ./logue-sdk/tools/logue-cli/get_logue_cli_linux.sh

      - name: Build oscillator
        run: make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: minilogue-xd-oscillator
          path: |
            *.mnlgxdunit
          retention-days: 30

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Logue SDK tools
        run: |
          chmod +x ./logue-sdk/tools/gcc/get_gcc_linux.sh
          chmod +x ./logue-sdk/tools/logue-cli/get_logue_cli_linux.sh
          ./logue-sdk/tools/gcc/get_gcc_linux.sh
          ./logue-sdk/tools/logue-cli/get_logue_cli_linux.sh

      - name: Build oscillator
        run: make

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.mnlgxdunit
          generate_release_notes: true
